### ISSUE TITLE
中文目录下调用openjava失败

### ISSUE THREAD

**Issue by dfaofeng** [zkonge/mirua#4]
![image](https://user-images.githubusercontent.com/14891398/93692332-662f6d00-fb24-11ea-8937-1c74710c2a75.png)

**Comment by zkonge** [comment]
java本体就不能存在于路径包含中文的位置。

举个例子，目前版本的 openjdk 在运行位于中文目录的本体 `./java喵/bin/java.exe` 会因为没法搞定 Windows 的编码而直接报错退出，因为找不到自己的模块。

脑测有这么几种解决方法：
1. 打开 `控制面板->区域->管理->更改系统区域设置->使用Unicode...全球语言支持` 支持，但没真的试过，可能可以，也可能把别的软件搞炸。
2. 向 openjdk 反馈

**Comment by zkonge** [comment]
后续：感谢热心群友，openjdk8 经过测试是可以跑在中文目录下的，似乎还是 openjdk 自己的问题。个人不太想用过气的 java8（
