### ISSUE TITLE
目前无法下载了

### ISSUE THREAD

**Issue by wqy0916** [zkonge/mirua#5]
1:下载不了
2:希望能增加一个滑动模块的下载和32位自动下载native 
谢谢

**Comment by zkonge** [comment]
jre地址已更新。
具体插件还是建议自己下。
不过因为我现在不用mirai了，滑动模块是个啥。

**Comment by zkonge** [comment]
加了插件下载支持（只要这个插件放上maven），不过配置文件还是要自己填一下的

**Comment by wqy0916** [comment]
谢谢 目前来说不滑动就不能登陆了
